//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.25 at 10:20:45 PM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ecb.int/vocabulary/2002-08-01/eurofxref", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package models.iggy.zap.fx;
